name: Lint and Type Check

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install ruff mypy

      - name: Ruff
        run: |
          ruff --version
          ruff check src test_installation.py

      - name: Mypy
        run: |
          mypy --version
          mypy --ignore-missing-imports src

