name: Smoke Tests

on:
  push:
  pull_request:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install minimal dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-smoke.txt

      - name: Run smoke tests
        run: |
          python test_installation.py

